-- MySQL Script generated by MySQL Workbench
-- Sat May 16 16:58:32 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `role` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`theater_room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`theater_room` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `capacity` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`movie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `description` LONGTEXT NULL,
  `duration` INT NULL,
  `genre` VARCHAR(100) NULL,
  `poster_url` VARCHAR(500) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`exhibition_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`exhibition_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`theater_room_exhibition_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`theater_room_exhibition_type` (
  `theater_room_id` INT NOT NULL,
  `exhibition_type_id` INT NOT NULL,
  INDEX `fk_TheaterRoomExhibitionType_TheaterRoom_idx` (`theater_room_id` ASC) VISIBLE,
  INDEX `fk_TheaterRoomExhibitionType_ExhibitionType1_idx` (`exhibition_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_TheaterRoomExhibitionType_TheaterRoom`
    FOREIGN KEY (`theater_room_id`)
    REFERENCES `mydb`.`theater_room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TheaterRoomExhibitionType_ExhibitionType1`
    FOREIGN KEY (`exhibition_type_id`)
    REFERENCES `mydb`.`exhibition_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`seat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`seat` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `seat_row` VARCHAR(5) NULL,
  `seat_column` INT NULL,
  `theater_room_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_seat_theater_room1_idx` (`theater_room_id` ASC) VISIBLE,
  CONSTRAINT `fk_seat_theater_room1`
    FOREIGN KEY (`theater_room_id`)
    REFERENCES `mydb`.`theater_room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`seat_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`seat_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `seat_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_seat_category_seat1_idx` (`seat_id` ASC) VISIBLE,
  CONSTRAINT `fk_seat_category_seat1`
    FOREIGN KEY (`seat_id`)
    REFERENCES `mydb`.`seat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ticket_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ticket_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `price_multiplier` DECIMAL(4,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`showtime`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`showtime` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `starts_at` DATETIME NOT NULL,
  `ends_at` DATETIME NOT NULL,
  `status` VARCHAR(20) NOT NULL,
  `movie_id` INT NOT NULL,
  `theater_room_id` INT NOT NULL,
  `exhibition_type_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_showtime_movie1_idx` (`movie_id` ASC) VISIBLE,
  INDEX `fk_showtime_theater_room1_idx` (`theater_room_id` ASC) VISIBLE,
  INDEX `fk_showtime_exhibition_type1_idx` (`exhibition_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_showtime_movie1`
    FOREIGN KEY (`movie_id`)
    REFERENCES `mydb`.`movie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_showtime_theater_room1`
    FOREIGN KEY (`theater_room_id`)
    REFERENCES `mydb`.`theater_room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_showtime_exhibition_type1`
    FOREIGN KEY (`exhibition_type_id`)
    REFERENCES `mydb`.`exhibition_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reservation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `total_price` DECIMAL(10,2) NOT NULL,
  `status` VARCHAR(20) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `expires_at` DATETIME NOT NULL,
  `user_id` INT NOT NULL,
  `showtime_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reservation_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_reservation_showtime1_idx` (`showtime_id` ASC) VISIBLE,
  CONSTRAINT `fk_reservation_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservation_showtime1`
    FOREIGN KEY (`showtime_id`)
    REFERENCES `mydb`.`showtime` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`seat_reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`seat_reservation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `base_price` DECIMAL(10,2) NOT NULL,
  `discount_amount` DECIMAL(10,2) NOT NULL,
  `final_price` DECIMAL(10,2) NOT NULL,
  `status` VARCHAR(20) NOT NULL,
  `seat_id` INT NOT NULL,
  `ticket_type_id` INT NOT NULL,
  `reservation_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_seat_reservation_seat1_idx` (`seat_id` ASC) VISIBLE,
  INDEX `fk_seat_reservation_ticket_type1_idx` (`ticket_type_id` ASC) VISIBLE,
  INDEX `fk_seat_reservation_reservation1_idx` (`reservation_id` ASC) VISIBLE,
  CONSTRAINT `fk_seat_reservation_seat1`
    FOREIGN KEY (`seat_id`)
    REFERENCES `mydb`.`seat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_seat_reservation_ticket_type1`
    FOREIGN KEY (`ticket_type_id`)
    REFERENCES `mydb`.`ticket_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_seat_reservation_reservation1`
    FOREIGN KEY (`reservation_id`)
    REFERENCES `mydb`.`reservation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ticket` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(100) NOT NULL,
  `issued_at` DATETIME NOT NULL,
  `status` VARCHAR(20) NOT NULL,
  `seat_reservation_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ticket_seat_reservation1_idx` (`seat_reservation_id` ASC) VISIBLE,
  CONSTRAINT `fk_ticket_seat_reservation1`
    FOREIGN KEY (`seat_reservation_id`)
    REFERENCES `mydb`.`seat_reservation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`payment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `amount` DECIMAL(10,2) NOT NULL,
  `payment_method` VARCHAR(50) NULL,
  `payment_status` VARCHAR(20) NOT NULL,
  `paid_at` DATETIME NULL,
  `reservation_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_payment_reservation1_idx` (`reservation_id` ASC) VISIBLE,
  CONSTRAINT `fk_payment_reservation1`
    FOREIGN KEY (`reservation_id`)
    REFERENCES `mydb`.`reservation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
